### ISSUE TITLE
Packaged game : Drone camera freezing inplace

### ISSUE THREAD

**Issue by geevargs** [orig74/UE4PyhtonBridge#5]
![screenshot from 2018-03-23 14 32 26](https://user-images.githubusercontent.com/29235421/37854214-24fbd838-2ea7-11e8-8136-fd15b068e42a.png)

**Comment by geevargs** [comment]
Ensure condition failed: TextureRHI [File:/home/airspace/UnrealEngine/Engine/Source/Runtime/OpenGLDrv/Private/OpenGLRenderTarget.cpp] [Line: 855] 

[2018.03.23-21.29.16:602][592]LogStats: FPlatformStackWalk::StackWalkAndDump -  0.018 s
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: === Handled ensure: ===
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: 
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: Ensure condition failed: TextureRHI [File:/home/airspace/UnrealEngine/Engine/Source/Runtime/OpenGLDrv/Private/OpenGLRenderTarget.cpp] [Line: 855]
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: 
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: Stack: 
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: [Callstack]  00  0x000000000259e0cf  FLinuxPlatformStackWalk::CaptureStackBackTrace(unsigned long long*, unsigned int, void*)
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: [Callstack]  01  0x0000000002472d05  FGenericPlatformStackWalk::StackWalkAndDump(char*, unsigned long, int, void*)
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: [Callstack]  02  0x000000000259e089  FLinuxPlatformStackWalk::StackWalkAndDumpEx(char*, unsigned long, int, unsigned int, void*)
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: [Callstack]  03  0x00000000025e7148  FDebug::EnsureFailed(char const*, char const*, int, wchar_t const*)
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: [Callstack]  04  0x00000000025d344f  FDebug::OptionallyLogFormattedEnsureMessageReturningFalse(bool, char const*, char const*, int, wchar_t const*, ...)
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: [Callstack]  05  0x0000000003942ba6  FOpenGLDynamicRHI::RHIReadSurfaceData(FRHITexture*, FIntRect, TArray<FColor, FDefaultAllocator>&, FReadSurfaceDataFlags)
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: [Callstack]  06  0x000000000501dffe  PX4/Binaries/Linux/PX4() [0x501dffe]
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: [Callstack]  07  0x0000000005078543  PX4/Binaries/Linux/PX4() [0x5078543]
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: [Callstack]  08  0x0000000002498056  FNamedTaskThread::ProcessTasksNamedThread(int, bool)
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: [Callstack]  09  0x00000000024975ae  FNamedTaskThread::ProcessTasksUntilQuit(int)
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: [Callstack]  10  0x00000000039cd32a  RenderingThreadMain(FEvent*)
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: [Callstack]  11  0x00000000039db992  FRenderingThread::Run()
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: [Callstack]  12  0x00000000024cdbf7  FRunnableThreadPThread::Run()
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: [Callstack]  13  0x00000000024ab440  FRunnableThreadPThread::_ThreadProc(void*)
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: [Callstack]  14  0x00007ff02bf5d184  /lib/x86_64-linux-gnu/libpthread.so.0(+0x8184) [0x7ff02bf5d184]
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: [Callstack]  15  0x00007ff02b0e7ffd  /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7ff02b0e7ffd]
[2018.03.23-21.29.16:602][592]LogOutputDevice: Error: 
[2018.03.23-21.29.16:602][592]LogStats:                SubmitErrorReport -  0.000 s
[2018.03.23-21.29.16:639][592]LogStats:                    SendNewReport -  0.020 s
[2018.03.23-21.29.16:640][592]LogStats:             FDebug::EnsureFailed -  0.038 s
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/airspace/DroneSimLab/UE4PyhtonBridge/src/Wrappers/pyinit.py", line 43, in PyTick
    next(main_loop_iter)
  File "../../DroneSimLab/demos/unreal_proxies/two_drones/unreal_proxy.py", line 117, in main_loop
    img=ph.GetTextureData(drone_textures[drone_index])
  File "/home/airspace/DroneSimLab/UE4PyhtonBridge/src/Wrappers/phandlers.py", line 102, in GetTextureData
    tmp_capture_mem=np.zeros(req_mem_sz,'uint8')
MemoryError
ending main loop!!

**Comment by geevargs** [comment]
I ran a few test cases to diagnose the error:
It appears that the numpy array is full beyond its capacity and thus giving this error.
It only seems to be a problem in packaged games in my 2nd PC it crashes regardless of data being sent to the FDM but this problem is not seen in my dev platform.
after 1min of running.
**tmp_capture_mem=np.zeros(req_mem_sz,'uint8')
MemoryError**

I believe this error has occurred because I ran it for weeks continuously

I have linux 14,04 and have 12 gb free space on my PC.
Unreal 4.17.2

**Comment by orig74** [comment]
Try to add 2 lines between 101 and 102 in  the file "/home/airspace/DroneSimLab/UE4PyhtonBridge/src/Wrappers/phandlers.py",
del tmp_capture_mem # free memory
print('requested size id:',req_mem_sz) #for debug

**Comment by geevargs** [comment]
I did the print('requested size id:',req_mem_sz) #for debug
requested size id: 4
requested size id: 8294400

**Comment by geevargs** [comment]
del tmp_capture_mem # free memory didnt work...should i redo set_path.py...
This occurs only in binary mode on one Pc but works fine on my dev platform.

**Comment by orig74** [comment]
Can you track the memory usage during the simulation on both systems (the dev platform and the other PC)?  You can do it with tools like system monitor. It will help us understand the difference.

**Comment by geevargs** [comment]
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND   
 13978 airspace  20   0 6954920 2.059g 195052 R 208.4 13.2   3:34.98 PX4    ----- production platform
19340 sujith    20   0 6126620 2.213g 205272 S 177.4  7.1   1:02.32 MyProject2+   ------dev platform

**Comment by geevargs** [comment]
The %memory usage is more than 200% and is 170+ in the dev platform.
Everything else is similar.

**Comment by geevargs** [comment]
Production platform:

![screenshot from 2018-03-27 16 34 40](https://user-images.githubusercontent.com/29235421/38000522-cd3ed2e2-31dc-11e8-8d02-0ade3e680b14.png)

**Comment by geevargs** [comment]
Dev platform

![screenshot from 2018-03-27 16_37_22](https://user-images.githubusercontent.com/29235421/38000650-74822978-31dd-11e8-9b77-f77146016f8d.png)

**Comment by orig74** [comment]
can you look if the memory usage is increasing? 
show me the resource graphs from the moment you open the application until it fails on both stations.

**Comment by geevargs** [comment]
Production platform:
![screenshot from 2018-03-28 11 37 53](https://user-images.githubusercontent.com/29235421/38049344-d8f7f398-327c-11e8-9717-bf9597f5199c.png)
![screenshot from 2018-03-28 11 38 05](https://user-images.githubusercontent.com/29235421/38049345-d90d071a-327c-11e8-85cc-03276ad7de67.png)
![screenshot from 2018-03-28 11 38 15](https://user-images.githubusercontent.com/29235421/38049346-d924682e-327c-11e8-82f3-b38dc7c9fa31.png)

**Comment by geevargs** [comment]
Dev Platform:
![screenshot from 2018-03-28 11 48 05](https://user-images.githubusercontent.com/29235421/38049980-82be3864-327e-11e8-8080-ab0c9b99ff7f.png)
![screenshot from 2018-03-28 11 48 27](https://user-images.githubusercontent.com/29235421/38049981-82d2dd46-327e-11e8-8170-3464c805a51a.png)
![screenshot from 2018-03-28 11 49 05](https://user-images.githubusercontent.com/29235421/38049982-82e9a152-327e-11e8-8060-c03fa375c522.png)
![screenshot from 2018-03-28 11 49 26](https://user-images.githubusercontent.com/29235421/38049983-82ff58bc-327e-11e8-889d-6d67ec79158f.png)
![screenshot from 2018-03-28 11 50 26](https://user-images.githubusercontent.com/29235421/38049984-8313969c-327e-11e8-8272-10ccfcf92a28.png)
![screenshot from 2018-03-28 11 51 09](https://user-images.githubusercontent.com/29235421/38049986-832956a8-327e-11e8-95cf-32c1962370ff.png)

**Comment by orig74** [comment]
I don't really understand why it fails since I can't see any memory issue. but let's try and bypass the problem for now.
try and change line 82 in "phandlers.py" to something like:
`tmp_capture_mem=np.zeros(8294400,'uint8')`
this hopefully will eliminate the need to reallocating the memory (line 102).

**Comment by geevargs** [comment]
I tried  tmp_capture_mem=np.zeros(8294400,'uint8') didnt work but i tried the same line in line 102 and the simulator lasted longer but crashed completely after 2 iterations.
thats 1 more than before

**Comment by orig74** [comment]
Can you show me what it was printing when it crashed (the debug lines we added)?

**Comment by geevargs** [comment]
Just the debug lines

![screenshot from 2018-03-28 15 12 39](https://user-images.githubusercontent.com/29235421/38059254-90f2f228-329a-11e8-9792-4f81b0f18723.png)

**Comment by geevargs** [comment]
With the  tmp_capture_mem=np.zeros(8294400,'uint8')
![screenshot from 2018-03-28 15 15 32](https://user-images.githubusercontent.com/29235421/38059342-f1e3938a-329a-11e8-899c-bbb9198748bc.png)

**Comment by orig74** [comment]
I can see the problem now, the requested size is huge. This means some kind of memory corruption somewhere. Try and add some debug prints of the size before the allocation. 
`print(txt_index,'req_mem_sz is ',sz,ret)`
you should see more the one print of this output. send me all of the outputs of that line

**Comment by geevargs** [comment]
print(tex_ptr,'req_mem_sz is ',sz,ret) at  line 101
![screenshot from 2018-03-28 16 39 39](https://user-images.githubusercontent.com/29235421/38062039-c3bc6ed0-32a6-11e8-9e5d-ddff41dac699.png)

**Comment by geevargs** [comment]
it doesnt print txt_index..its not declared before line 168 
and the program fails before reaching it.

**Comment by geevargs** [comment]
I declared txt_index earlier and did a few prints.
![screenshot from 2018-03-29 16 38 33](https://user-images.githubusercontent.com/29235421/38118475-c04e7454-336f-11e8-93f3-3f9313be5132.png)

**Comment by orig74** [comment]
I can see the problem now. 
I think it is not directly related to the framework. in the output it says:
Ensure condition fails: TextureRHI: ....

I had this issue before I don't quite remember how I solved it :<
I found a reference to it:
https://answers.unrealengine.com/questions/718835/418h-must-be-first-header-when-packaging-plugin.html?sort=oldest

In any case, I will have a look later this week at my code and let you know if and when I changed anything.

**Comment by orig74** [comment]
have you tried the solution in the link?
adding to the *.build.cs file the line:
```
PCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;
```

**Comment by geevargs** [comment]
PCHUsage = ModuleRules.PCHUsageMode.UseExplicitOrSharedPCHs;
![screenshot from 2018-04-09 18-32-45](https://user-images.githubusercontent.com/29235421/38531394-75afaa5e-3c24-11e8-935c-b4f0d0275a54.png)

**Comment by geevargs** [comment]
Didnt work but I am gonna keep working on it...do you have any other suggestions?

**Comment by orig74** [comment]
Since it is PCH related I would try to change the order of the include files in the Source of the game. I think this is how I solved it when had this error.
